[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quilleval"
version = "0.1.0"
description = "Prompt & LLM Output Evaluation with plugins, CIs, and run registry"
requires-python = ">=3.9"
